### PR TITLE
Add `Hyperf Plugin`

### PR DESCRIPTION
**Pull request by huangdijia**
This is a Pest plugin that enables your Hyperf project's Pest to run within a Swoole-based coroutine environment.

### CODE REVIEW

**Comment by felixdorn** [comment]
Hey! Thank you for your PR. 

Could you provide an explanation, in your README, or at least here, of what this does and **how does it differ from the Parallel mode in Pest (https://pestphp.com/docs/optimizing-tests#content-parallel-testing)** ?

We want the Awesome Pest repository to be welcoming and fun to explore and an empty README goes against that, it's not just a list of plugins.

**Comment by huangdijia** [comment]
Unlike `Parallel mode`, `pest-plugin-hyperf` is primarily designed to enable `$kernel->handle()` to run within a coroutine environment instead of executing test cases in parallel.

[README](https://github.com/friendsofhyperf/pest-plugin-hyperf/blob/main/README.md ) has been updated.

**Comment by huangdijia** [comment]
This is a demonstration based on Hyperf and pest-plugin-hyperf.

https://github.com/huangdijia/hyperf-pest-demo

**Comment by felixdorn** [comment]
Thank you!

**Pull request merged**
